import CodeEditor from "@/components/CodeEditor";
import Form from "@/components/Form";
import ResearchBuilder from "@/components/ResearchBuilder";
import { Container, Divider, Title } from "@mantine/core";
import Head from "next/head";

const ResearchPage = () => {
  return (
    <>
      <Head>
        <title>Research</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xs" px="sm" pt="xl">
        <ResearchBuilder />
      </Container>
    </>
  );
};

export default ResearchPage;
